### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by OncePunchedMan** [curche/no-spoilers-please#2]
When using dark mode, it doesn't change the app to the dark mode version. Text becomes white on white.

Workaround:

- change to light mode
- set settings
- change back to dark mode
much love and thank for fixing

**Comment by curche** [comment]
Should be fixed by cdd9bc774683d22dd249942050dde9433a49768f
You can try it out in the [Latest release 1.2.1](https://github.com/curche/no-spoilers-please/releases/tag/1.2.1)
